# имя Flutter приложения
# обычно данное имя используется в качестве
# названия pub-пакета. Это важно лишь в том случае,
# если вы разрабатываете свой pub-пакет и собираетесь
# выложить его в общий доступ
# имя Android и iOS приложения впоследствии
# можно будет изменить отдельно для каждой из платформ
# имя так же является названием коренной папки
# что видно впри иморте классов 
name: tasks

# краткое описание на английском
description: "A new Flutter project."

# я не собираюсь опубликовывать pub-пакет
# и поэтому
# запрещаем команду flutter publish
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# версия Android и iOS приложения
# состоит из 2 частей, разделенных знаком плюса
# первая часть - это имя версии, которое будет
# видно для пользователей, например 1.1.5
# вторая часть позволяет Google Play и Apple Store
# отличать разные версии нашего приложения
version: 1.0.0+1

# версия Dart SDK
environment:
  sdk: '>=3.2.4 <4.0.0'

# блок зависимостей
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_storage:  ^2.1.1
  d_input: ^0.1.2


  # использование иконок для Cupertino компонентов
  # Cupertino компоненты - это компоненты в стили iOS
  cupertino_icons: ^1.0.2

# зависимости для разработки
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# в данной секции вы можете подключить шрифты и assets файлы
flutter:

  # Следующая строка гарантирует, что шрифт Material Icons включен
  # в ваше приложение, чтобы вы могли использовать значки 
  # в классе материалов Icons.
  uses-material-design: true

  # Чтобы добавить ресурсы в ваше приложение, добавьте раздел ресурсов, например:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Чтобы добавить пользовательские шрифты в ваше приложение, 
  # добавьте раздел шрифтов здесь, в этом разделе "flutter". 
  # Каждая запись в этом списке должна иметь ключ «семейство» с 
  # названием семейства шрифтов и ключ «шрифты» со списком, 
  # содержащим актив и другие дескрипторы для шрифта. Например:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
